version: "3.8"
name: yarr

include:
  - path: services/bazarr/docker-compose.yml
  - path: services/calibre/docker-compose.yml
  - path: services/calibre-web/docker-compose.yml
  - path: services/flaresolverr/docker-compose.yml
  - path: services/jackett/docker-compose.yml
  - path: services/lazylibrarian/docker-compose.yml
  - path: services/lidarr/docker-compose.yml
  - path: services/mylar/docker-compose.yml
  - path: services/nginx/docker-compose.yml
  - path: services/nordvpn/docker-compose.yml
  - path: services/nzbget/docker-compose.yml
  - path: services/nzbhydra2/docker-compose.yml
  - path: services/plex/docker-compose.yml
  - path: services/protonvpn/docker-compose.yml
  - path: services/prowlarr/docker-compose.yml
  - path: services/qbittorrent/docker-compose.yml
  - path: services/radarr/docker-compose.yml
  - path: services/readarr/docker-compose.yml
  - path: services/sonarr/docker-compose.yml
  - path: services/emby/docker-compose.yml
  - path: services/jdownloader/docker-compose.yml
  - path: services/audiobookshelf/docker-compose.yml
  - path: services/pihole/docker-compose.yml
  #- path: services/authentik/docker-compose.yml
  #- path: services/gitea/docker-compose.yml
  # - path: services/janitorr/docker-compose.yml
  #- path: services/kavita/docker-compose.yml
  #- path: services/omby/docker-compose.yml
  